name: 'create-pagerduty-incident'

description: 'An action that will create a PagerDuty incident.'
inputs:
  pagerduty-api-key:
    description: 'The PagerDuty API Key that allows access to your services.'
    required: true
  email:
    description: 'The email address of a valid PagerDuty user on the account associated with the auth token.'
    required: false
  service-id:
    description: 'The PagerDuty Service ID to create the incident for.'
    required: true
  title:
    description: 'The title of the PagerDuty Incident that will be created. '
    required: true
  body:
    description: 'The body of the PagerDuty Incident that will be created.'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
